spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vehicle_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Cholao}
spring.datasource.driver-class-name=org.postgresql.Driver

#CONFIGURACIÓN JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Esto asegura que Flyway use las mismas credenciales
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

#SEGURIDAD JWT
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=28800000
